export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS'
export const ADD_PRODUCT_CART_FAIL = 'ADD_PRODUCT_CART_FAIL'

export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'

export const CREATE_PRODUCT_TOTAL = 'CREATE_PRODUCT_TOTAL'

export const PLUS_QUANTITY_PRODUCT = 'PLUS_QUANTITY_PRODUCT'

export const MINUS_QUANTITY_PRODUCT = 'MINUS_QUANTITY_PRODUCT'
