export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS'
export const ADD_PRODUCT_CART_FAIL = 'ADD_PRODUCT_CART_FAIL'

export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'
export const REMOVE_PRODUCT_CART_SUCCESS = 'REMOVE_PRODUCT_CART_SUCCESS'
export const REMOVE_PRODUCT_CART_FAIL = 'REMOVE_PRODUCT_CART_FAIL'

export const CREATE_PRODUCT_TOTAL = 'CREATE_PRODUCT_TOTAL'
export const CREATE_PRODUCT_TOTAL_SUCCESS = 'CREATE_PRODUCT_TOTAL_SUCCESS'
export const CREATE_PRODUCT_TOTAL_FAIL = 'CREATE_PRODUCT_TOTAL_FAIL'
